POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
    "codUsu": "002",
    "nome": "maria catariana",
    "email": "catarina1@gmail.com",
    "senha": "12231",
    "telefone": "40028921",
    "dtCadastro": "2001-07-06T00:00:00",
    "ativo": "true",
    "tipoUsuario": {
        "tipoUsuarioId": 1
    }
}

###

POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
    "email": "catarina1@gmail.com",
    "senha": "12231"
}

###

GET http://localhost:8080/api/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjk3ODQwMjYzLCJleHAiOjE2OTc5MjY2NjN9.Lr-w8btG1v_nIZlLYmmerZHEWTx6PwPB8Byv88Sp2Ow


