
# adicionar
POST http://localhost:8080/api/formas-pagamento
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3ODQ2MjA5LCJleHAiOjE2OTc5MzI2MDl9.uKUege62i4Qd12VroDRg-VmvI-WirlgMiOA_7SsG0ao

{
    "codPgt": "COD004",
    "descricao": "pix"
}

###

# obterTodos
GET http://localhost:8080/api/formas-pagamento