POST http://localhost:8080/api/formas-pagamento
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3Njg3NTk0LCJleHAiOjE2OTc3NzM5OTR9.7lL_WUIEOke0AeWvfncDsmP8iEvAsLR-lzUESR-HCeU

{
    "codPgt": "COD127",
    "descricao": "Descrição da Forma de Pagamento",
    "ativo": true
}

###

GET http://localhost:8080/api/formas-pagamento