POST http://localhost:8080/api/pedidos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3OTE3NTQyLCJleHAiOjE2OTgwMDM5NDJ9.t3xVrqjEdJiO2V6Hbo_HLBkKpl4d9bLrVwOBI0CJXAM
# adicionar 

{
    "nrPedido": "000001",
    "descTotal": 0.0,
    "acresTotal": 0.0,
    "obs": "Venda",
    "usuario": {
        "usuarioId": 2
    },
    "formaDePagamento": {
        "pgtId": 1
    },
    "itens": [

        {
            "vlUn": 10.0,
            "qtd": 1,
            "vlDesc": 0,
            "vlAcres": 0,
            "produto": {
                "produtoId": 1
            }
        }
    ]  
}

###

# obterTodos

GET http://localhost:8080/api/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3NzU5MzkxLCJleHAiOjE2OTc4NDU3OTF9.uk7dT5fUl2B1-B3mAZrsNwKDbRsBaiZznDmttBduH5k


###
# obterPorId
GET http://localhost:8080/api/pedidos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3NzU5MzkxLCJleHAiOjE2OTc4NDU3OTF9.uk7dT5fUl2B1-B3mAZrsNwKDbRsBaiZznDmttBduH5k
