POST http://localhost:8080/api/pedidos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3ODQ4OTkzLCJleHAiOjE2OTc5MzUzOTN9.w7N3Vpb2PosyiHj1UohSfsxZn3oI96GR8uSjFh3ZNiM

{
    "nrPedido": "pedido71",
    "descTotal": 10.0,
    "acresTotal": 0.0,
    "obs": "Venda",
    "usuario": {
        "usuarioId": 1
    },
    "formaDePagamento": {
        "pgtId": 2
    },
    "itens": [

        {
            "vlUn": 20.0,
            "qtd": 10,
            "vlDesc": 0,
            "vlAcres": 0,
            "produto": {
                "produtoId": 1
            }    
        }
    ]

}

###

# obterTodos

GET http://localhost:8080/api/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3NzU5MzkxLCJleHAiOjE2OTc4NDU3OTF9.uk7dT5fUl2B1-B3mAZrsNwKDbRsBaiZznDmttBduH5k
