POST http://localhost:8080/api/pedidos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjk3OTI0NzgzLCJleHAiOjE2OTgwMTExODN9.jvX5MEoeqMC8Dt294k036cJvFKF8G-DybRaEfBoldC4
# adicionar 

{
    "nrPedido": "000003",
    "descTotal": 0.0,
    "acresTotal": 0.0,
    "obs": "Venda",
    "usuario": {
        "usuarioId": 3
    },
    "formaDePagamento": {
        "pgtId": 1
    },
    "itens": [

        {
            "vlUn": 10.0,
            "qtd": 1,
            "vlDesc": 0,
            "vlAcres": 0,
            "produto": {
                "produtoId": 1
            }
        }
    ]  
}

###

# obterTodos

GET http://localhost:8080/api/pedidos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3NzU5MzkxLCJleHAiOjE2OTc4NDU3OTF9.uk7dT5fUl2B1-B3mAZrsNwKDbRsBaiZznDmttBduH5k


###
# obterPorId
GET http://localhost:8080/api/pedidos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3NzU5MzkxLCJleHAiOjE2OTc4NDU3OTF9.uk7dT5fUl2B1-B3mAZrsNwKDbRsBaiZznDmttBduH5k
