POST http://localhost:8080/api/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzQ5OTQxLCJleHAiOjE2OTc4MzYzNDF9.8ziEyhDzQ_RMhY8YGscZB1T2xDh6YgtgDgoFCK4Qju8

{
    "codProd": "000001",
    "prodNome": "Chave de Fenda",
    "qtdEst": 50,
    "precoVenda": 10.50,
    "obs": "Observação do Produto",
    "ativo": true,
    "categoria": {
        "categoriaId": 1
    }

}

###

GET http://localhost:8080/api/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NzQ5OTQxLCJleHAiOjE2OTc4MzYzNDF9.8ziEyhDzQ_RMhY8YGscZB1T2xDh6YgtgDgoFCK4Qju8