
# cadastra um usuario
POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
    "codUsu": "usuario2",
    "nome": "leticia carla",
    "email": "batata@gmail.com",
    "senha": "1234",
    "telefone": "40028921",
    "tipoUsuario": {
        "tipoUsuarioId": 1
    }
}

###
GET  http://localhost:8080/api/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjk3ODQwMjYzLCJleHAiOjE2OTc5MjY2NjN9.Lr-w8btG1v_nIZlLYmmerZHEWTx6PwPB8Byv88Sp2Ow

###

# retorna um usuario baseado no email
GET http://localhost:8080/api/usuarios/email/admin@admin.com
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjk3ODQwMjYzLCJleHAiOjE2OTc5MjY2NjN9.Lr-w8btG1v_nIZlLYmmerZHEWTx6PwPB8Byv88Sp2Ow

###

# efetua um login
POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "senha": "123456"
}

###